import type { FactoryLot, FactoryProfile } from './types'

export const factoryProfile: FactoryProfile = {
  id: 'factory-nakhon-sawan-01',
  factoryName: 'Nakhon Sawan Sugar Mill',
  officerName: 'คุณมณีรัตน์',
  province: 'นครสวรรค์',
  buyingSeason: '2025/26',
  dailyCapacityTon: 2400,
}

export const factoryLots: FactoryLot[] = [
  {
    id: 'lot-001',
    farmerName: 'สมชาย ใจดี',
    farmName: 'Somchai Farm',
    district: 'ตาคลี',
    province: 'นครสวรรค์',
    plotName: 'แปลง A',
    cropType: 'อ้อยสด',
    cropVariety: 'Khon Kaen 3',
    quantityTon: 35,
    ccs: 12.4,
    harvestDate: '2026-03-15',
    deliveryWindow: 'วันนี้ 13:00-15:00',
    status: 'pending_review',
    risk: 'low',
    traceabilityId: 'ZB-2026-001',
    tokenId: 'ZBT-2026-001',
    carbonSavedKg: 1200,
    pricePerTon: 2400,
    evidence: ['harvest-evidence.png', 'residue-management.png'],
    notes: 'หลักฐานไม่เผาครบ มีรูปเศษซากหลังเก็บเกี่ยวและพิกัดแปลงตรงกับระบบ',
  },
  {
    id: 'lot-002',
    farmerName: 'สมศรี รักเกษตร',
    farmName: 'Somsi Green Farm',
    district: 'พยุหะคีรี',
    province: 'นครสวรรค์',
    plotName: 'แปลง B',
    cropType: 'อ้อยสด',
    cropVariety: 'LK92-11',
    quantityTon: 28,
    ccs: 11.8,
    harvestDate: '2026-03-16',
    deliveryWindow: 'พรุ่งนี้ 09:00-11:00',
    status: 'verified',
    risk: 'medium',
    traceabilityId: 'ZB-2026-002',
    tokenId: 'ZBT-2026-002',
    carbonSavedKg: 840,
    pricePerTon: 2320,
    evidence: ['sugarcane-close-up.png', 'harvest-evidence.png'],
    notes: 'ผ่านการตรวจเบื้องต้น แต่ควรตรวจคิวรถก่อนรับเข้าโรงงาน',
  },
  {
    id: 'lot-003',
    farmerName: 'ประเสริฐ แปลงใหญ่',
    farmName: 'Prasert Cane Group',
    district: 'บรรพตพิสัย',
    province: 'นครสวรรค์',
    plotName: 'แปลง C',
    cropType: 'อ้อยสด',
    cropVariety: 'K88-92',
    quantityTon: 44,
    ccs: 10.9,
    harvestDate: '2026-03-17',
    deliveryWindow: 'รอจัดคิว',
    status: 'needs_info',
    risk: 'high',
    traceabilityId: 'ZB-2026-003',
    carbonSavedKg: 0,
    pricePerTon: 2180,
    evidence: ['residue-management.png'],
    notes: 'ต้องการรูปยืนยันหลังตัดเพิ่ม เพราะพบสัญญาณความเสี่ยงในพื้นที่ข้างเคียง',
  },
]
